# Path of clouds
# path vio cloud: "/media/ce.debeunne/HDD/datasets/ISAE/2024-01-24-CNES/stereo_cloud/cloud_tour_pierre1"
path vio cloud: "/home/deos/ce.debeunne/Documents/phd/developpement/SLAM_eval/dense_stereo_fisheye/cloud"
path lidar cloud: "/media/ce.debeunne/HDD/datasets/ISAE/2024-01-24-CNES/raw_data/tour_pierre1_raw/lidar0/data"

# threshold for scan / cloud association (in s)
dt_min: 0.025

# Init transformation for IC (config 30 degrees)
T_init: [-0.101265, -0.420947,   0.90142,  0.643826,
-0.994502,  0.018423,  -0.10312,  0.335025,
0.0268019, -0.906904 ,-0.420495, -0.451624,
        0,         0,         0,         1]

# Beginning and end of loop
i_start: 1
i_stop: 2
n_cloud_to_eval: 1

