# Path of trajectory
path vio: "/home/deos/ce.debeunne/Documents/phd/developpement/SLAM_eval/result/CNES_2024/tour_butte2_vio.csv"

# Path of left / right images
path cam left: "/media/ce.debeunne/HDD/datasets/ISAE/2024-01-24-CNES/raw_data/tour_butte2_raw/cam0/data"
path cam right: "/media/ce.debeunne/HDD/datasets/ISAE/2024-01-24-CNES/raw_data/tour_butte2_raw/cam1/data"

# threshold for left / right association (in s)
dt_min: 0.0025

# dense stereo parameters
vfov: 90
ndisp: 80
wsize: 11